control_frequency: 30.0
gripper_enabled: false
max_episode_steps: 1000

cartesian_control_param_config: null
joint_control_param_config: null

robot_config:
  robot_type: "franka"
  time_to_home: 3.0
  publish_frequency: 50.0

gripper_config:
  from_yaml: "gripper_right.yaml"

camera_configs:
  - camera_name: "primary"
    camera_frame: "primary_link"
    resolution: [256, 256]
    camera_color_image_topic: "image_raw"
    camera_color_info_topic: "camera_info"

sensor_configs: []
